name: 'documentation-tracker-action'

description: 'GitHub Documentation Tracker Action'

inputs:
  paths:
    description: 'Paths to where the documentation you want to track is stored'
    required: false
  default-owners:
    description: 'Owners for all the documentation and are tagged automatically'
    required: false

runs:
  using: "composite"
  steps:
    - name: test
      run: |
        pip install pipenv && pipenv install --system --deploy
        python3 "${{ github.action_path }}/documentation.py" \
          -p "${{ inputs.paths }}" \
          -o "${{ inputs.default-owners }}" \
          --github-token ${{ github.token }} \
          --github-repository ${{ github.repository }} \
          --workflow-event ${{ github.event_name }}
      shell: bash