name: 'documentation-tracker-action'

description: 'GitHub Documentation Tracker Action'

inputs:
  paths:
    description: 'Paths to where the documentation you want to track is stored'
    required: false
  default-owners:
    description: 'Owners for all the documentation and are tagged automatically'
    required: false
  label-closing:
    description: 'Label which creates a PR with updates'
    required: true

runs:
  using: "composite"
  steps:
    - name: test
      run: |
        echo "::group::Installing" && \
          pip install pipenv && pipenv install --system --deploy && \
          echo "::endgroup::"
        python3 "${{ github.action_path }}/documentation.py" \
          -p "${{ inputs.paths }}" \
          -o "${{ inputs.default-owners }}" \
          -c "${{ inputs.label-closing }}" \
          --github-token ${{ github.token }} \
          --github-repository ${{ github.repository }} \
          --github-event ${{ github.event_path }} \
          --workflow-event ${{ github.event_name }}

      shell: bash